name: GuiCreator
version: '1.0-SNAPSHOT'
main: com.guicreator.guiCreator.GuiCreator
api-version: '1.21'
author: Hoogkids
softdepend:
  - Vault
  - PlaceholderAPI
commands:
  guicreator:
    description: Open the visual GUI management framework canvas.
    permission: guicreator.admin
    usage: /guicreator [create/edit/delete/list/help]
    aliases:
      - creategui
      - gc